use QLBH
GO
CREATE VIEW View1 AS
SELECT*FROM SANPHAM;
GO
SELECT*FROM View1

GO
CREATE VIEW View2 AS
SELECT TOP 100 PERCENT SANPHAM.MASP, HANGSX.TENHANG, SANPHAM.SOLUONG, SANPHAM.MAUSAC, SANPHAM.GIABAN,SANPHAM.DONVITINH,SANPHAM.MOTA
FROM SANPHAM
INNER JOIN HANGSX ON SANPHAM.MAHANGSX=HANGSX.MAHANGSX
ORDER BY SANPHAM.GIABAN DESC;

GO
CREATE VIEW View3 AS
SELECT SANPHAM.MASP, SANPHAM.TENSP, HANGSX.TENHANG,SANPHAM.SOLUONG,SANPHAM.MAUSAC, SANPHAM.GIABAN, SANPHAM.DONVITINH,SANPHAM.MOTA
FROM SANPHAM
INNER JOIN HANGSX ON SANPHAM.MAHANGSX=HANGSX.MAHANGSX

GO
CREATE VIEW View4 AS
SELECT*FROM NHANVIEN
WHERE GIOITINH=N'NỮ' AND PHONG=N'KeToan'

GO
CREATE VIEW View5 AS
select NHAP.SOHDN, SANPHAM.MASP, SANPHAM.TENSP, NHAP.SOLUONGN, NHAP.DONGIAN, NHAP.NGAYNHAP, NHANVIEN.TENNV, NHANVIEN.PHONG
from HANGSX,NHANVIEN,SANPHAM,NHAP
where NHAP.NGAYNHAP=N'2017'

GO
CREATE VIEW View6 AS
SELECT TOP 10 SANPHAM.MASP, SANPHAM.TENSP, SANPHAM.GIABAN
FROM SANPHAM
ORDER BY GIABAN DESC

GO
CREATE VIEW View7 AS
SELECT MASP, SUM(DONGIAN*SOLUONGN) AS'Tong Tien Nhap'
FROM NHAP
WHERE YEAR(NGAYNHAP)=2020
GROUP BY MASP

GO
CREATE VIEW View8 AS
SELECT PHONG, COUNT(*) AS'So Luong NV Nu'
FROM NHANVIEN 
WHERE GIOITINH=N'Nu'
GROUP BY PHONG

GO
CREATE VIEW View9 AS
SELECT HANGSX.TENHANG, SUM(NHAP.SOLUONGN) AS 'TongSoLuongNhap'
FROM HANGSX
INNER JOIN SANPHAM ON HANGSX.MAHANGSX= SANPHAM.MAHANGSX
INNER JOIN NHAP ON SANPHAM.MASP = NHAP.MASP
WHERE YEAR(NHAP.NGAYNHAP) = 2020
GROUP BY HANGSX.TENHANG

GO
CREATE VIEW View10 AS
SELECT NHANVIEN.TENNV, SUM(XUAT.SOLUONGX * SANPHAM.GIABAN) AS 'Tong Tien Xuat'
FROM NHANVIEN
INNER JOIN XUAT ON NHANVIEN.MANV = XUAT.MANV
INNER JOIN SANPHAM ON XUAT.MASP = SANPHAM.MASP
WHERE YEAR(XUAT.NGAYXUAT) = 2020
GROUP BY NHANVIEN.TENNV

GO
CREATE VIEW View11 AS
SELECT MANV, SUM(SOLUONGN*DONGIAN) AS TỔNG
FROM NHAP 
WHERE MONTH(NGAYNHAP) = 7 AND YEAR(NGAYNHAP) = 2020
GROUP BY MANV
HAVING SUM(SOLUONGN*DONGIAN) >100.000

GO
CREATE VIEW View12 AS
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM
LEFT JOIN NHAP N ON SANPHAM.MASP = N.MASP
LEFT JOIN XUAT X ON SANPHAM.MASP = X.MASP
WHERE N.SOLUONGN IS NOT NULL AND X.MASP IS NULL
GROUP BY SANPHAM.MASP, SANPHAM.TENSP

GO
CREATE VIEW View13 AS
SELECT HANGSX.TENHANG, COUNT(SANPHAM.MASP) AS'So Luong San Pham'
FROM HANGSX
INNER JOIN SANPHAM ON HANGSX.MAHANGSX = SANPHAM.MAHANGSX
GROUP BY HANGSX.TENHANG

GO
CREATE VIEW View14 AS
SELECT TOP 10 SANPHAM.MASP, SANPHAM.TENSP, SANPHAM.GIABAN
FROM SANPHAM
ORDER BY GIABAN DESC

GO
CREATE VIEW View15 AS
SELECT PHONG, COUNT(*) AS'So Luong NV Nam'
FROM NHANVIEN 
WHERE GIOITINH=N'Nam'
GROUP BY PHONG